services:
  neo4j:
    image: neo4j:5.20
    container_name: socialNetwork
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=socialNetwork/adminPassword
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  couchdb:
    image: couchdb:3.3
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=test123
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  neo4j_data:
  neo4j_logs:
  couchdb_data:
